name: Tenant Optimizer CI/CD

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Copy frontend build to backend/static
        run: |
          rm -rf backend/static
          mkdir -p backend/static
          cp -r frontend/dist/* backend/static/

      - name: Make startup.sh executable
        run: chmod +x backend/startup.sh

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Deploy Bicep
        run: |
          az deployment group create --resource-group tenant-optimizer-rg --template-file infra/main.bicep --parameters @infra/main.parameters.json

      - name: Zip backend for deployment
        run: |
          cd backend
          zip -r ../backend.zip .

      - name: Set Azure App Settings (Key Vault references)
        run: |
          az webapp config appsettings set \
            --resource-group tenant-optimizer-rg \
            --name tenant-optimizer-web \
            --settings \
              OPENAI_KEY="@Microsoft.KeyVault(SecretUri=https://tenant-optimizer-kv.vault.azure.net/secrets/OPENAI-KEY/2b8ec4122c464727ab6e1ef90fe535cb)" \
              COSMOS_DB_CONNECTION_STRING="@Microsoft.KeyVault(SecretUri=https://tenant-optimizer-kv.vault.azure.net/secrets/COSMOS-DB-CONNECTION-STRING/916edc421c9a4e9c96c8f48dd60cafde)" \
              AZURE_CLIENT_ID="@Microsoft.KeyVault(SecretUri=https://tenant-optimizer-kv.vault.azure.net/secrets/AZURE-CLIENT-ID/1d4b42be349340f1853e55a2e8c5a7d5)" \
              AZURE_CLIENT_SECRET="@Microsoft.KeyVault(SecretUri=https://tenant-optimizer-kv.vault.azure.net/secrets/AZURE-CLIENT-SECRET/01423d2be6ba442e930030514388480a)" \
              AZURE_TENANT_ID="@Microsoft.KeyVault(SecretUri=https://tenant-optimizer-kv.vault.azure.net/secrets/AZURE-TENANT-ID/be90843f165b4ec0a2960275359a6e13)"

      - name: Wait for App Service restart
        run: |
          sleep 60
          az webapp restart --resource-group tenant-optimizer-rg --name tenant-optimizer-web

      - name: Deploy Backend + Frontend to Azure Web App
        run: |
          az webapp deploy --resource-group tenant-optimizer-rg --name tenant-optimizer-web --src-path backend.zip --type zip